"""empty message

Revision ID: 22e2f4695aed
Revises: 554478d21eec
Create Date: 2014-10-17 16:42:34.099746

"""

# revision identifiers, used by Alembic.
revision = '22e2f4695aed'
down_revision = '554478d21eec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote_option', sa.Column('value', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote_option', 'value')
    ### end Alembic commands ###
