"""empty message

Revision ID: 3a9e303d3a51
Revises: bf0e1428d49
Create Date: 2014-11-08 17:20:55.944038

"""

# revision identifiers, used by Alembic.
revision = '3a9e303d3a51'
down_revision = 'bf0e1428d49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('open', sa.DATETIME(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'open')
    ### end Alembic commands ###
