"""empty message

Revision ID: 3ff6c6195e11
Revises: 4860efb4597f
Create Date: 2014-10-17 16:10:28.630904

"""

# revision identifiers, used by Alembic.
revision = '3ff6c6195e11'
down_revision = '4860efb4597f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('personalized', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'personalized')
    ### end Alembic commands ###
