"""empty message

Revision ID: 554478d21eec
Revises: 3ff6c6195e11
Create Date: 2014-10-17 16:25:17.725265

"""

# revision identifiers, used by Alembic.
revision = '554478d21eec'
down_revision = '3ff6c6195e11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vote_id'], ['vote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vote_options')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote_options',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('vote_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['vote_id'], [u'vote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vote_option')
    ### end Alembic commands ###
