"""empty message

Revision ID: 8c8a09830b
Revises: 257210b3be18
Create Date: 2014-10-25 14:56:28.967350

"""

# revision identifiers, used by Alembic.
revision = '8c8a09830b'
down_revision = '257210b3be18'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    ### end Alembic commands ###
