"""empty message

Revision ID: bf0e1428d49
Revises: 8c8a09830b
Create Date: 2014-11-08 15:50:02.808969

"""

# revision identifiers, used by Alembic.
revision = 'bf0e1428d49'
down_revision = '8c8a09830b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('close', sa.DATETIME(), nullable=True))
    op.drop_column('vote', 'personalized')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('personalized', sa.BOOLEAN(), nullable=True))
    op.drop_column('vote', 'close')
    ### end Alembic commands ###
